# 1234
name: build

on: [push, pull_request]

jobs:
  publish-s3-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r github-actions-testing.zip . -i /home/runner/work/github-actions-testing
      - name: pwd
        run: |
          pwd
          ls -ltr
        shell: bash   
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWSACCESSKEYID }}
          aws_secret_access_key: ${{ secrets.AWSSECRETKEY}}
          aws_bucket: ${{ secrets.S3_BUCKET_NAME }}
          source_path: "/home/runner/work/github-actions-testing/github-actions-testing/github-actions-testing.zip"
          destination_path: "/artifacts"
