# 123
name: pipeline to archieve artifact in S3

on: [push, pull_request]

jobs:
  publish-s3-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2
      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}
      - name: converting repo to zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src
      - name: checking out files
        run: |
          pwd
          ls -ltr ./artifacts
        shell: bash
      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETKEY}}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          SOURCE_DIR: './artifacts'
          AWS_REGION: 'ap-south-1'
