# 1234
name: pipeline to archieve artifact in S3

on: [push, pull_request]

jobs:
  publish-s3-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checking out repo
      - uses: montudor/action-zip@v1
        name: converting repo to zip
        with:
          args: zip -qq -r github-actions-testing.zip . -i /home/runner/work/github-actions-testing
      - name: checking out files
        run: |
          pwd
          ls -ltr
        shell: bash  
      - uses: shallwefootball/s3-upload-action@master
        name: uploading to s3      
        with:
          aws_key_id: ${{ secrets.AWSACCESSKEYID }}
          aws_secret_access_key: ${{ secrets.AWSSECRETKEY}}
          aws_bucket: ${{ secrets.S3_BUCKET_NAME }}
          source_dir: "/home/runner/work/github-actions-testing/github-actions-testing"
          destination_dir: "/artifacts"
