name: build

on: [push, pull_request]

jobs:
  publish-s3-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r github-actions-testing.zip . -i /home/runner/work/github-actions-testing
      - name: pwd
        run: |
          pwd
          ls -ltr
        shell: bash   
      - name: Upload to S3 as artifact
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: "/home/runner/work/github-actions-testing/github-actions-testing/github-actions-testing.zip"
          AWS_REGION: 'ap-south-1'
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
#         S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETKEY }}
